// Shared VCS → ReviewGraph dataset builder (GitHub, GitLab, and future hosts).
//
// Platform adapters fetch merge/pull requests and pass normalized records here.
// The output matches the canonical model shape used by assess, questions, and seed.

import { mergeRulesFromPrFiles } from "./reviewgraphConfig.js";

export const SECURITY_RE = /(auth|token|session|secret|password|passwd|credential|crypto|oauth|jwt|login|permission|acl|secur|sign|cert|key)/i;
export const AI_RE = /\b(ai|a\.i\.|copilot|cursor|chatgpt|gpt|llm|codegen|gemini|claude|codex|auto[- ]?generated|ai[- ]?generated|generated by)\b/i;
const ROOT_DIRS = new Set(["src", "lib", "app", "source", "sources", "pkg"]);

export const slug = (s) => String(s || "").replace(/[^a-z0-9]+/gi, "_").replace(/^_+|_+$/g, "").toLowerCase().slice(0, 90);
export const svcId = (name) => `svc_${slug(name)}`;
export const modId = (name) => `mod_${slug(name)}`;
export const fileId = (path) => `file_${slug(path)}`;
export const devId = (login) => `dev_${slug(login)}`;
export const teamId = (token) => `team_${slug(token)}`;

export function pathToServiceModule(path) {
  const clean = String(path).replace(/\\/g, "/");
  const segs = clean.split("/");
  segs.pop();
  const dirs = segs.filter((s) => s && !ROOT_DIRS.has(s.toLowerCase()));
  if (dirs.length === 0) return { serviceName: "root", moduleName: "root" };
  return { serviceName: dirs[0], moduleName: dirs.slice(0, 2).join("/") };
}

export function globToRegExp(glob) {
  let g = glob.trim();
  if (g.startsWith("/")) g = g.slice(1);
  const re = g
    .replace(/[.+^${}()|[\]\\]/g, "\\$&")
    .replace(/\*\*/g, "::DSTAR::")
    .replace(/\*/g, "[^/]*")
    .replace(/::DSTAR::/g, ".*");
  return new RegExp(`^${re}`);
}

export function parseCodeowners(text) {
  const rules = [];
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.replace(/#.*$/, "").trim();
    if (!line) continue;
    const [pattern, ...owners] = line.split(/\s+/);
    if (!owners.length) continue;
    rules.push({ pattern, regex: globToRegExp(pattern === "*" ? "**" : pattern), owners });
  }
  return rules;
}

export function ownersFor(path, rules) {
  let match = null;
  for (const rule of rules) if (rule.regex.test(path)) match = rule;
  return match ? match.owners : [];
}

export function importsFromPatch(patch) {
  if (!patch) return [];
  const specs = [];
  for (const line of patch.split("\n")) {
    if (!line.startsWith("+") || line.startsWith("+++")) continue;
    const body = line.slice(1).trim();
    const quoted = body.match(/(?:import\s.*?from\s*|import\s*|require\s*\(\s*)['"]([^'"]+)['"]/);
    if (quoted) {
      specs.push(quoted[1]);
      continue;
    }
    const pyFrom = body.match(/^from\s+(\.+[\w./]+)\s+import\s+/);
    if (pyFrom) specs.push(pyFrom[1]);
  }
  return specs;
}

export function resolveRelativeImport(fromPath, spec) {
  if (!spec.startsWith(".")) return null;
  const fromDir = fromPath.replace(/\\/g, "/").split("/").slice(0, -1);
  let rest = spec;
  while (rest.startsWith(".")) {
    if (rest.startsWith("../")) {
      fromDir.pop();
      rest = rest.slice(3);
    } else if (rest.startsWith("./")) {
      rest = rest.slice(2);
    } else if (rest.startsWith("..")) {
      fromDir.pop();
      rest = rest.slice(2);
    } else break;
  }
  const tail = rest.includes("/") ? rest : rest.replace(/\./g, "/");
  return pathToServiceModule(`${fromDir.concat(tail.split("/")).filter(Boolean).join("/")}.ts`);
}

/**
 * @param {object} opts
 * @param {{ name: string, url: string, primaryLanguage?: string }} opts.repo
 * @param {object} opts.rules - parsed .reviewgraph.json
 * @param {ReturnType<parseCodeowners>} opts.codeowners
 * @param {string|null} opts.flagshipMrIid - optional MR/PR number to open first
 * @param {Array<{
 *   iid: number|string,
 *   title: string,
 *   body?: string,
 *   state: string,
 *   authorLogin?: string,
 *   isAiAssisted?: boolean,
 *   labels?: string[],
 *   files: Array<{ path: string, patch?: string, additions?: number, deletions?: number }>,
 *   comments?: Array<{ id?: string|number, login?: string, path?: string, body?: string }>,
 *   reviewerLogins?: string[]
 * }>} opts.mergeRequests
 */
export function buildDatasetFromMergeRequests({ repo, rules: inputRules = {}, codeowners = [], flagshipMrIid, mergeRequests }) {
  const rules = mergeRulesFromPrFiles(inputRules, mergeRequests);
  const securityGlobs = (rules.securityGlobs || []).map(globToRegExp);

  const services = new Map();
  const modules = new Map();
  const filesMap = new Map();
  const developers = new Map();
  const teams = new Map();
  const pullRequests = [];
  const reviewComments = [];
  const moduleDepSet = new Map();

  const ensureDeveloper = (login) => {
    if (!login) return null;
    const id = devId(login);
    if (!developers.has(id)) developers.set(id, { id, name: login, login, teamId: null });
    return id;
  };

  const isSecurity = (path) => SECURITY_RE.test(path) || securityGlobs.some((re) => re.test(path));

  const ensureServiceModule = (path) => {
    const { serviceName, moduleName } = pathToServiceModule(path);
    const sId = svcId(serviceName);
    if (!services.has(sId)) services.set(sId, { id: sId, name: serviceName, criticality: "medium", teamId: null });
    const mId = modId(moduleName);
    if (!modules.has(mId)) modules.set(mId, { id: mId, name: moduleName, layer: "domain", serviceId: sId });
    return { sId, mId };
  };

  for (const mr of mergeRequests) {
    const number = mr.iid;
    const authorId = ensureDeveloper(mr.authorLogin);
    const aiHaystack = `${mr.title || ""} ${mr.body || ""} ${(mr.labels || []).join(" ")}`;
    const isAiAssisted = mr.isAiAssisted ?? AI_RE.test(aiHaystack);

    const prFileIds = [];
    let securityCount = 0;
    let churn = 0;

    for (const f of mr.files || []) {
      const path = f.path;
      if (!path) continue;
      const { sId, mId } = ensureServiceModule(path);
      const security = isSecurity(path);
      if (security) securityCount += 1;
      churn += (f.additions || 0) + (f.deletions || 0);

      const fId = fileId(path);
      const fileNode = filesMap.get(fId) || { id: fId, path, moduleId: mId, securitySensitive: security };
      filesMap.set(fId, fileNode);
      prFileIds.push(fId);

      for (const spec of importsFromPatch(f.patch)) {
        const resolved = resolveRelativeImport(path, spec);
        if (!resolved) continue;
        const targetMod = modId(resolved.moduleName);
        if (targetMod !== mId) {
          ensureServiceModule(`${resolved.serviceName}/${resolved.moduleName}/_.ts`);
          moduleDepSet.set(`${mId}->${targetMod}`, { source: mId, target: targetMod, reason: `imports ${spec}` });
        }
        for (const d of rules.decisions || []) {
          if (!d.fromService || !d.toService) continue;
          if (svcId(d.fromService) === sId && svcId(d.toService) === svcId(resolved.serviceName)) {
            fileNode.introducesDependency = { fromServiceId: svcId(d.fromService), toServiceId: svcId(d.toService) };
          }
        }
      }
    }

    for (const c of mr.comments || []) {
      const reviewerId = ensureDeveloper(c.login);
      if (!reviewerId) continue;
      const cPath = c.path;
      if (!cPath) continue;
      reviewComments.push({
        id: `comment_${number}_${slug(c.id ?? `${c.login}_${cPath}`)}`,
        prId: `PR-${number}`,
        reviewerId,
        fileId: fileId(cPath),
        issueTypeId: null,
        sentiment: "neutral",
        body: c.body || "",
        embeddingText: c.body || ""
      });
    }

    for (const login of mr.reviewerLogins || []) {
      const reviewerId = ensureDeveloper(login);
      for (const fId of prFileIds) {
        reviewComments.push({
          id: `review_${number}_${slug(login)}_${slug(fId)}`,
          prId: `PR-${number}`,
          reviewerId,
          fileId: fId,
          issueTypeId: null,
          sentiment: "neutral",
          body: `Reviewed by ${login}`,
          embeddingText: ""
        });
      }
    }

    const baseRiskScore = Math.min(
      90,
      10 +
        Math.min(prFileIds.length * 2, 20) +
        Math.min(securityCount * 10, 30) +
        Math.min(Math.round(churn / 50), 20) +
        (isAiAssisted ? 10 : 0)
    );

    pullRequests.push({
      id: `PR-${number}`,
      number,
      title: mr.title || `MR ${number}`,
      authorId,
      state: mr.state,
      isAiAssisted,
      baseRiskScore,
      summary: (mr.body || mr.title || "").slice(0, 600),
      files: prFileIds
    });
  }

  const fileByService = new Map();
  for (const file of filesMap.values()) {
    const svc = modules.get(file.moduleId)?.serviceId;
    if (svc && !fileByService.has(svc)) fileByService.set(svc, file.path);
  }
  for (const [sId, samplePath] of fileByService) {
    const owners = ownersFor(samplePath, codeowners);
    if (!owners.length) continue;
    const owner = owners[0];
    const tId = teamId(owner);
    if (!teams.has(tId)) teams.set(tId, { id: tId, name: owner, domain: "" });
    const service = services.get(sId);
    if (service) service.teamId = tId;
    if (!owner.includes("/")) {
      const login = owner.replace(/^@/, "");
      const dId = ensureDeveloper(login);
      const dev = developers.get(dId);
      if (dev && !dev.teamId) dev.teamId = tId;
    }
  }

  const adrs = (rules.adrs || []).map((a) => ({
    id: a.id,
    title: a.title || a.id,
    governsServiceId: a.governsService ? svcId(a.governsService) : null,
    status: a.status || "accepted"
  }));

  const decisions = (rules.decisions || []).map((d) => ({
    id: d.id,
    summary: d.summary || `${d.fromService} must not depend on ${d.toService}`,
    policy: d.policy || "",
    status: "active",
    aboutServiceId: d.fromService ? svcId(d.fromService) : null,
    adrId: d.adrId || null,
    forbids: d.fromService && d.toService ? { fromServiceId: svcId(d.fromService), toServiceId: svcId(d.toService) } : undefined
  }));

  const repoKey = slug(repo.name);
  const flagship = flagshipMrIid ? `PR-${flagshipMrIid}` : pullRequests[0]?.id || null;

  return enrichDatasetFromRules(
    {
      flagshipEntityId: flagship,
      repositories: [{ id: `repo_${repoKey}`, name: repo.name, url: repo.url, primaryLanguage: repo.primaryLanguage }],
      teams: [...teams.values()],
      developers: [...developers.values()],
      services: [...services.values()],
      modules: [...modules.values()],
      moduleDeps: [...moduleDepSet.values()],
      files: [...filesMap.values()],
      issueTypes: DEFAULT_ISSUE_TYPES,
      riskPatterns: [],
      pullRequests,
      reviewComments,
      aiChanges: [],
      securityFindings: [],
      releases: [],
      deployments: [],
      incidents: [],
      adrs,
      decisions,
      lessons: []
    },
    rules,
    mergeRequests
  );
}

const DEFAULT_ISSUE_TYPES = [
  { id: "issue_security", name: "Security Sensitive Change", severity: "high", description: "Touches authentication, tokens, or secrets." },
  { id: "issue_coupling", name: "Architecture Coupling", severity: "high", description: "Cross-layer or forbidden service dependency." }
];

const DEFAULT_RISK_PATTERNS = [
  {
    id: "pattern_cross_layer",
    name: "CrossLayerShortcut",
    severity: "high",
    description: "Code bypasses bounded contexts and imports another layer directly.",
    embeddingText: "cross layer import service boundary architecture coupling etl ios",
    causes: ["issue_coupling"]
  },
  {
    id: "pattern_coupling_regression",
    name: "LayerCouplingRegression",
    severity: "high",
    description: "Reintroduces a direct dependency that previously caused production issues.",
    embeddingText: "etl ios sync coupling regression reverted incident duplicate writes",
    causes: ["issue_coupling"]
  },
  {
    id: "pattern_scattered_auth",
    name: "ScatteredCredentialHandling",
    severity: "high",
    description: "Credentials or tokens handled outside the central security path.",
    embeddingText: "password token secret credential log auth neo4j load",
    causes: ["issue_security"]
  }
];

/** Attach repo rules, historical context, and inferred risk signals (generic for any VCS ingest). */
export function enrichDatasetFromRules(dataset, rules = {}, mergeRequests = []) {
  const filesById = new Map(dataset.files.map((f) => [f.id, f]));
  const patchByPath = new Map();
  for (const mr of mergeRequests) {
    for (const f of mr.files || []) {
      if (f.path && f.patch) patchByPath.set(f.path, f.patch);
    }
  }

  dataset.riskPatterns = [
    ...DEFAULT_RISK_PATTERNS,
    ...(rules.riskPatterns || []).map((p) => ({
      id: p.id,
      name: p.name,
      severity: p.severity || "high",
      description: p.description || "",
      embeddingText: p.embeddingText || p.description || p.name,
      causes: p.causes || ["issue_coupling", "issue_security"]
    }))
  ];

  dataset.incidents = [
    ...(rules.incidents || []).map((i) => ({
      id: i.id,
      title: i.title,
      severity: i.severity || "SEV2",
      impactedServices: (i.impactedServices || []).map((s) => svcId(s)),
      tracedToPr: i.tracedToPr || null,
      rootCause: i.rootCause || "Architecture regression",
      summary: i.summary || i.title
    }))
  ];

  dataset.lessons = [
    ...(rules.lessons || []).map((l) => ({
      id: l.id,
      statement: l.statement,
      fromIncident: l.fromIncident,
      recommends: l.recommends || "",
      appliesToModuleIds: (l.appliesToModuleIds || []).map((m) => modId(m)),
      appliesToPatternIds: l.appliesToPatternIds || []
    }))
  ];

  for (const prior of rules.priorPullRequests || []) {
    const prId = prior.id || `PR-${prior.number}`;
    if (dataset.pullRequests.some((p) => p.id === prId)) continue;
    const fileIds = (prior.files || []).map((path) => fileId(path));
    for (const path of prior.files || []) {
      ensureFileInDataset(dataset, path, filesById);
      const file = filesById.get(fileId(path));
      if (file && prior.coupling?.from && prior.coupling?.to) {
        file.introducesDependency = {
          fromServiceId: svcId(prior.coupling.from),
          toServiceId: svcId(prior.coupling.to)
        };
      }
    }
    dataset.pullRequests.push({
      id: prId,
      number: prior.number,
      title: prior.title,
      authorId: null,
      state: prior.state || "reverted",
      isAiAssisted: false,
      baseRiskScore: prior.baseRiskScore || 70,
      summary: prior.summary || prior.title,
      files: fileIds
    });
  }

  const aiChanges = [...dataset.aiChanges];
  const securityFindings = [...dataset.securityFindings];

  for (const pr of dataset.pullRequests) {
    if (pr.state === "reverted" || pr.id.startsWith("PR-hist")) continue;
    for (const fId of pr.files || []) {
      const file = filesById.get(fId);
      if (!file) continue;
      const patchText = patchByPath.get(file.path) || "";
      if (file.introducesDependency) {
        pushAiPattern(aiChanges, pr.id, file.id, "pattern_cross_layer", 0.88);
        pushAiPattern(aiChanges, pr.id, file.id, "pattern_coupling_regression", 0.84);
      }
      if (file.securitySensitive) {
        pushAiPattern(aiChanges, pr.id, file.id, "pattern_scattered_auth", 0.8);
      }
      if (
        /(password|secret|token|api_key)\s*=\s*["'][^"']+["']/i.test(patchText) ||
        /log.*password|password.*log/i.test(patchText)
      ) {
        securityFindings.push({
          id: `finding_${pr.id}_${slug(file.path)}`,
          prId: pr.id,
          fileId: file.id,
          severity: "high",
          title: "Hardcoded credential in diff",
          description: "Patch introduces inline secrets or default passwords."
        });
      }
    }
  }

  dataset.aiChanges = aiChanges;
  dataset.securityFindings = securityFindings;
  return dataset;
}

function ensureFileInDataset(dataset, path, filesById) {
  const fId = fileId(path);
  if (filesById.has(fId)) return;
  const { serviceName, moduleName } = pathToServiceModule(path);
  const sId = svcId(serviceName);
  const mId = modId(moduleName);
  if (!dataset.services.some((s) => s.id === sId)) {
    dataset.services.push({ id: sId, name: serviceName, criticality: "high", teamId: null });
  }
  if (!dataset.modules.some((m) => m.id === mId)) {
    dataset.modules.push({ id: mId, name: moduleName, layer: "domain", serviceId: sId });
  }
  const file = { id: fId, path, moduleId: mId, securitySensitive: SECURITY_RE.test(path) };
  dataset.files.push(file);
  filesById.set(fId, file);
}

function pushAiPattern(aiChanges, prId, fileId, patternId, score) {
  const id = `ai_${prId}_${patternId}_${fileId}`;
  if (aiChanges.some((c) => c.id === id)) return;
  aiChanges.push({
    id,
    prId,
    fileId,
    summary: `Graph-inferred signal: matches ${patternId}`,
    embeddingText: patternId,
    patterns: [{ patternId, score }]
  });
}

export function parseReviewgraphJson(text) {
  if (!text) return {};
  try {
    return normalizeReviewgraphRules(JSON.parse(text));
  } catch {
    return {};
  }
}

/** Map nested reviewgraph-config shapes to the flat rules ingest expects. */
export function normalizeReviewgraphRules(raw) {
  if (!raw || typeof raw !== "object") return {};
  const rules = { ...raw };
  const globs = [...(rules.securityGlobs || [])];
  if (Array.isArray(raw.security?.sensitivePaths)) {
    globs.push(...raw.security.sensitivePaths);
  }
  if (globs.length) rules.securityGlobs = [...new Set(globs)];

  const decisions = [...(rules.decisions || [])];
  const forbidden = raw.architecture?.forbiddenDependencies;
  if (Array.isArray(forbidden)) {
    for (const [i, entry] of forbidden.entries()) {
      if (typeof entry === "string") continue;
      decisions.push({
        id: entry.id || `forbidden_${i}`,
        summary: entry.summary || `${entry.from || entry.fromService} must not depend on ${entry.to || entry.toService}`,
        policy: entry.policy || "",
        fromService: entry.from || entry.fromService,
        toService: entry.to || entry.toService,
        adrId: entry.adrId || null
      });
    }
  }
  if (decisions.length) rules.decisions = decisions;

  const adrs = [...(rules.adrs || [])];
  if (Array.isArray(raw.architecture?.adrs)) adrs.push(...raw.architecture.adrs);
  if (adrs.length) rules.adrs = adrs;

  return rules;
}
